#ifndef GNSS_SIGNAL_H
#define GNSS_SIGNAL_H
#include "gnss_common.h"

#ifdef __cplusplus
extern "C" {
#endif

/* =========================================================================
 * L1: GPS Signal Structure (ICD-GPS-200, IS-GPS-200)
 * ========================================================================= */

/** C/A code: Gold code of length 1023, generated by two 10-bit LFSRs */
typedef struct {
    int32_t prn;              /* GPS PRN number (1-32) */
    int32_t code[1023];       /* ±1 valued chips */
} gnss_ca_code_t;

/** P(Y) code descriptor (military, encrypted; modeled parametrically) */
typedef struct {
    int32_t prn;
    int64_t chip_count;       /* P-code chip count (~2.35×10¹⁴ per week) */
    double  chip_rate;        /* 10.23 Mcps */
} gnss_p_code_t;

/** GPS signal frequency band */
typedef enum {
    GNSS_BAND_L1  = 0,
    GNSS_BAND_L2  = 1,
    GNSS_BAND_L5  = 2,
    GNSS_BAND_E1  = 3,   /* Galileo */
    GNSS_BAND_E5a = 4,   /* Galileo */
    GNSS_BAND_B1I = 5,   /* BeiDou B1I */
    GNSS_BAND_B2I = 6    /* BeiDou B2I */
} gnss_band_t;

/** Frequency and wavelength for a band */
typedef struct {
    gnss_band_t band;
    double      freq_hz;       /* Carrier frequency [Hz] */
    double      wavelength_m;  /* Carrier wavelength [m] */
    double      chip_rate;     /* Ranging chip rate [cps] */
} gnss_band_desc_t;

/* -------------------------------------------------------------------------
 * L2: Gold Code Generation — G1/G2 shift register
 * ------------------------------------------------------------------------- */

/**
 * @brief G1/G2 polynomial phase selector for C/A code
 *
 * G1 = 1 + X³ + X¹⁰  (polynomial 1023 octal)
 * G2 = 1 + X² + X³ + X⁶ + X⁸ + X⁹ + X¹⁰ (polynomial 1715 octal)
 *
 * Each PRN uses a specific G2-tap combination (phase selector).
 */
typedef struct {
    uint16_t g1_register;     /* 10-bit G1 LFSR state */
    uint16_t g2_register;     /* 10-bit G2 LFSR state */
    int32_t  g2_taps[2];      /* Tap indices for G2 output (chip index) */
} gnss_lfsr_state_t;

/* -------------------------------------------------------------------------
 * L2: Doppler Shift Model
 * ------------------------------------------------------------------------- */

/**
 * @brief Satellite-receiver relative velocity and Doppler
 *
 * Doppler shift: Δf = -f_carrier · (v_rel/c)
 * where v_rel = radial component of relative velocity (closure rate).
 *
 * Range-rate: ṁ = v_sat·e + v_rx·e
 * (e = unit LOS vector from rx to sat)
 */
typedef struct {
    double range_rate;        /* ṁ [m/s], + = receding */
    double doppler_shift;     /* Δf [Hz] at the carrier frequency */
    double relative_velocity[3]; /* v_sat - v_rx in ECEF [m/s] */
} gnss_doppler_t;

/* -------------------------------------------------------------------------
 * L2: Navigation Message — Ephemeris
 * ------------------------------------------------------------------------- */

/** Broadcast ephemeris parameters (Keplerian + perturbations) */
typedef struct {
    int32_t  prn;
    gnss_gpstime_t toe;       /* Time of ephemeris */

    /* Keplerian */
    double   sqrt_a;          /* √semi-major axis [√m] */
    double   e;               /* Eccentricity */
    double   i0;              /* Inclination at reference time [rad] */
    double   omega0;          /* Longitude of ascending node [rad] */
    double   w;               /* Argument of perigee [rad] */
    double   M0;              /* Mean anomaly at reference time [rad] */

    /* Harmonic perturbations */
    double   delta_n;         /* Mean motion correction [rad/s] */
    double   i_dot;           /* Rate of inclination [rad/s] */
    double   omega_dot;       /* Rate of RAAN [rad/s] */
    double   cuc, cus;        /* Latitude argument corrections [rad] */
    double   crc, crs;        /* Radius corrections [m] */
    double   cic, cis;        /* Inclination corrections [rad] */

    /* Clock parameters */
    double   af0;             /* Clock bias [s] */
    double   af1;             /* Clock drift [s/s] */
    double   af2;             /* Clock drift rate [s/s²] */
    double   tgd;             /* Group delay differential [s] */

    int32_t  iod;             /* Issue of Data */
    int32_t  health;          /* Satellite health */
} gnss_ephemeris_t;

/** Almanac (coarse ephemeris, used for initial acquisition) */
typedef struct {
    int32_t  prn;
    double   sqrt_a;
    double   e;
    double   i0;
    double   omega0;
    double   w;
    double   M0;
    double   af0, af1;
    int32_t  week;
    int32_t  health;
} gnss_almanac_t;

/* -------------------------------------------------------------------------
 * L5: Signal Acquisition Parameters
 * ------------------------------------------------------------------------- */

/**
 * @brief Acquisition search space configuration
 *
 * Parallel code-phase search: FFT-based circular correlation.
 * Search dimensions: Doppler bin × code phase.
 */
typedef struct {
    double   doppler_min;     /* Search lower bound [Hz] */
    double   doppler_max;     /* Search upper bound [Hz] */
    double   doppler_step;    /* Doppler bin width [Hz] (typ. 500 Hz) */
    double   coherent_integ;  /* Coherent integration time [s] (typ. 1 ms) */
    int32_t  non_coherent;    /* Non-coherent accumulations */
    double   threshold;       /* Acquisition threshold (T/N₀ ratio) */
} gnss_acq_config_t;

/** Single acquisition result for one PRN */
typedef struct {
    int32_t  prn;
    int      acquired;        /* 1 if found, 0 otherwise */
    double   doppler_hz;      /* Estimated Doppler [Hz] */
    int32_t  code_phase;      /* Code phase [chips] */
    double   peak_ratio;      /* Peak-to-second-peak ratio */
    double   snr_db;          /* SNR estimate [dB] */
} gnss_acq_result_t;

/* -------------------------------------------------------------------------
 * API: Signal generation and analysis
 * ------------------------------------------------------------------------- */

/**
 * @brief Generate C/A code for PRN 1-37
 *
 * Implements the G1(1023) and G2(1715) LFSR with code-phase
 * selection per IS-GPS-200 Table 3-Ia.
 *
 * Complexity: O(1023)
 */
int gnss_ca_code_generate(int32_t prn, gnss_ca_code_t *code);
int gnss_ca_code_generate_shifted(int32_t prn, int32_t shift_chips,
                                   gnss_ca_code_t *code);

/**
 * @brief C/A code autocorrelation (normalized)
 *
 * Returns value at specific code-phase lag 0..1022.
 * Autocorrelation at lag=0 should be 1.0; max cross-correlation < 0.064.
 */
double gnss_ca_autocorrelation(const gnss_ca_code_t *code, int32_t lag);
double gnss_ca_crosscorrelation(const gnss_ca_code_t *a,
                                 const gnss_ca_code_t *b);

/* -------------------------------------------------------------------------
 * API: Doppler computation
 * ------------------------------------------------------------------------- */

/**
 * @brief Compute Doppler shift from relative velocity
 *
 * Δf = -f_carrier · (dot(e_sat, v_sat) - dot(e_rx, v_rx)) / c
 *
 * The unit LOS vector e points from receiver to satellite.
 */
gnss_doppler_t gnss_doppler_compute(gnss_ecef_t sat_pos, gnss_ecef_t rx_pos,
                                     const double sat_vel[3],
                                     const double rx_vel[3],
                                     double carrier_freq);

/**
 * @brief Convert Doppler shift to pseudorange rate
 *
 * ṁ = -(Δf / f_carrier) · c
 */
double gnss_doppler_to_range_rate(double doppler_hz, double carrier_freq);

/* -------------------------------------------------------------------------
 * API: Satellite position from ephemeris (L5 algorithm)
 * ------------------------------------------------------------------------- */

/**
 * @brief Compute ECEF satellite position from broadcast ephemeris
 *
 * Steps:
 * 1. Time from ephemeris: Δt = t - toe
 * 2. Corrected mean motion: n = √(GM / a³) + Δn
 * 3. Mean anomaly: M = M₀ + n·Δt
 * 4. Eccentric anomaly (Newton-Raphson): E - e·sin(E) = M
 * 5. True anomaly: ν = 2·atan(√((1+e)/(1-e))·tan(E/2))
 * 6. Argument of latitude: φ = ν + ω
 * 7. Perturbations: δu, δr, δi
 * 8. Corrected: u, r, i
 * 9. In-plane position: (r·cos(u), r·sin(u))
 * 10. Ω = Ω₀ + (Ω̇ - ω_e)·Δt - ω_e·toe
 * 11. ECEF rotation by Ω and i
 *
 * Reference: IS-GPS-200 §20.3.3.3.3.1, Tsui (2005) Ch.4
 */
int gnss_satpos_from_ephemeris(const gnss_ephemeris_t *eph,
                                gnss_gpstime_t t_rx,
                                gnss_ecef_t *sat_pos,
                                double sat_vel[3],
                                double *clock_bias);

/**
 * @brief Solve Kepler's equation M = E - e·sin(E) by Newton-Raphson
 *
 * Iterates E_{k+1} = E_k - (E_k - e·sin(E_k) - M) / (1 - e·cos(E_k))
 */
double gnss_kepler_solve(double M_rad, double eccentricity,
                          int max_iter, double tol);

/**
 * @brief Compute satellite clock correction
 *
 * Δt_sv = af0 + af1·Δt + af2·Δt² + Δt_rel
 * where Δt_rel = -2·√(GM·a)·e·sin(E)/c² (relativistic correction)
 */
double gnss_sat_clock_correction(const gnss_ephemeris_t *eph,
                                  double delta_t, double E_rad);

/** @brief Return frequency descriptor for a given band */
gnss_band_desc_t gnss_band_descriptor(gnss_band_t band);

#ifdef __cplusplus
}
#endif
#endif /* GNSS_SIGNAL_H */
